#!/usr/bin/env zsh
zmodload zsh/mathfunc

file=$1
a=1.0
omega=50.0
v=1.0
k=$(( omega/v ))
t=1.0

source $file
n=$(( int(t / dt) ))
#xr=$(( system_size_x / dx / 2 ))
xr=$(( system_size_x / dx ))

gnuplot -e "a='$a'; v='$v'; k='$k'; dx='$dx'; dt='$dt'; time='$time'; xr='$xr'; file='$file'; n='$n'" -p plot_diff.plt
